# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('delivery_address', models.CharField(max_length=30)),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2016, 12, 8, 16, 2, 25, 976535, tzinfo=utc))),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
