# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=30)),
                ('note_text', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=30)),
                ('is_pinned', models.BooleanField()),
            ],
        ),
    ]
