# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 13, 11, 13, 713637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 13, 11, 13, 713637, tzinfo=utc)),
        ),
    ]
